[package]
name = "weport"
version = "1.0.0"
description = "Weekly report application built with Tauri."
authors = ["Kwangsoo Seo", "monoslab <chps74@naver.com>"]
edition = "2024"
# Get rust version : rustc --version
rust-version = "1.94.0"
license = "Copyright (C) 2025 Monoslab. All rights reserved. This work is licensed under the Business Source License 1.1 - Monoslab (BUSL-1.1-Monoslab)."
readme = "README_KO.md"
default-run = "weport"

# Cargo resolver version is set to 3 to enable more advanced feature resolution.
# 1: 2015, 2018 Editions
# 2: 2021 Edition (https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html)
# 3: 2024 Edition (https://doc.rust-lang.org/edition-guide/rust-2024/cargo-resolver.html)
resolver = "3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "weport_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2.11.2", features = [] }
tauri-cli = "2.11.2"
tauri-plugin-opener = "2.5.4"
tauri-plugin-positioner = "2.3.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
once_cell = "1.21.4"
uuid = { version = "1.23.2", features = ["v4"] }
common = { version = "1.0.0", path = "src/common" }
libloading = "0.9.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.56.0"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[workspace]
members = [ "src/common" ]

[profile.dev]

[profile.release]
panic = "abort"         # Strip expensive panic clean-up logic
codegen-units = 1       # Compile crates one after another so the compiler can optimize better
lto = true              # Enables link-time optimizations
opt-level = "z"         # Optimize for binary size
strip = true            # Remove debug symbols
